# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-01-24 07:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('p_comment', models.IntegerField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('parent_name', models.CharField(max_length=64)),
                ('hot', models.IntegerField(default=1, max_length=11)),
                ('comment_type', models.IntegerField(choices=[(0, 'comment'), (1, 'thumb_up')], default=0)),
                ('comment', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('brief', models.CharField(blank=True, max_length=140, null=True)),
                ('sex', models.IntegerField(choices=[(1, 'Male'), (0, 'Female')], default=1)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('head_img', models.ImageField(upload_to='static/Commons/Images/user_face/')),
                ('attention', models.TextField(max_length=1000)),
                ('at_message', models.TextField(max_length=1000)),
                ('follow_list', models.ManyToManyField(blank=True, related_name='my_followers', to='web.UserProfile')),
                ('tags', models.ManyToManyField(to='web.Tags')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Weibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wb_type', models.IntegerField(choices=[(0, 'new'), (1, 'forward'), (2, 'collect')], default=0)),
                ('name', models.CharField(max_length=64)),
                ('text', models.CharField(max_length=140)),
                ('hot', models.IntegerField(default=0, max_length=11)),
                ('pictures_link_id', models.CharField(blank=True, max_length=128, null=True)),
                ('video_link_id', models.CharField(blank=True, max_length=128, null=True)),
                ('perm', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('forward_or_collect_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forward_or_collects', to='web.Weibo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserProfile')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='to_weibo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.Weibo'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.UserProfile'),
        ),
    ]
